#!/bin/sh

umask 022

if [ ! "${USERNAME}" ]
then
    echo
    echo could not determine USERNAME variable, halted...
    echo
    echo
    exit 1
fi


settitle 'matcalc [C]_I__C__D__I__' &&
bozoconf-gdevdef --prefix=/usr && make-gdevdef && 
rm -r /usr/include/matcalc &&
settitle 'matcalc _C_[I]_C__D__I__' &&
make-gdevdef install &&
chmod -R a+rX /usr/include/matcalc && exit 0
echo failed somewhere.......................................;
exit 1
